# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "chan-core/src/schema.rs"
#import_types = ["diesel::sql_types::*", "super::User_type::*"]   # <- note the extra import